# Gradle performance settings
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Minecraft and NeoForge versions
minecraft_version=26.2
minecraft_version_range=[26.2,27)
neo_version=26.2.0.75
neoforge_min_version=26.2.0.32-beta
neoforge_loader_version_range=[1,)

# Fabric
fabric_loader_version=0.19.5
fabric_min_loader_version=0.19.3
fabric_api_version=0.158.0+26.2

# Architectury
architectury_version=21.0.7

# Mod metadata
mod_id=mobfarmingsupplies
mod_name=MobFarmingSupplies
mod_license=MIT
mod_version=26.2.0.0
mod_group_id=net.bobofraggins.mobfarmingsupplies
