modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="assets/mobfarmingsupplies/icon.png"
description='''
MobFarmingSupplies - Mob processing utilities for Minecraft.
'''

[[mixins]]
config="mobfarmingsupplies-common.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jade"
type="optional"
versionRange="[26,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="tremendousstorage"
type="optional"
versionRange="[*,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="aquaculture"
type="optional"
versionRange="[*,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="aether_ii"
type="optional"
versionRange="[*,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="evilcraft"
type="optional"
versionRange="[*,)"
ordering="NONE"
side="BOTH"
